spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autofeed_project_db?logger=com.mysql.cj.log.Slf4JLogger&profileSQL=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
  database-platform: org.hibernate.dialect.MySQL5Dialect
  properties:
    hibernate.format_sql: true
    hibernate.show_sql: true
    hibernate.use_sql_comments: true
  mvc:
    view:
      suffix: .html